### ISSUE TITLE
Cannot log in to application if build configuration does not contain ui-data add-on (port to 1.0)

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-reports#210]
See original: https://github.com/Haulmont/jmix-reports/issues/209

### Description from original
1. Create project
2. Remove from `build.gradle` the `jmix-ui-data` dependency
3. Add Reports from market place or add the following dependencies:
```
implementation("io.jmix.reports:jmix-reports-starter")
implementation("io.jmix.reports:jmix-reports-rest-starter")
implementation("io.jmix.reports:jmix-reports-ui-starter")
```
4. Launch the app and try to log in.

**AR**
```
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: java.lang.IllegalArgumentException: MetaClass not found for class io.jmix.uidata.entity.UiSetting
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467) ~[spring-orm-5.3.8.jar:5.3.8]
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: java.lang.IllegalArgumentException: MetaClass not found for class io.jmix.uidata.entity.UiSetting

	at io.jmix.eclipselink.impl.JmixEclipselinkTransactionManager.doBegin(JmixEclipselinkTransactionManager.java:34) ~[jmix-eclipselink-1.0.1.jar:na]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.8.jar:5.3.8]
	at io.jmix.eclipselink.impl.JpaDataStore.beginLoadTransaction(JpaDataStore.java:297) ~[jmix-eclipselink-1.0.1.jar:na]
	at io.jmix.core.datastore.AbstractDataStore.loadList(AbstractDataStore.java:124) ~[jmix-core-1.0.1.jar:na]
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.loadList(UnconstrainedDataManagerImpl.java:112) ~[jmix-core-1.0.1.jar:na]
	at io.jmix.core.FluentLoader$ByQuery.list(FluentLoader.java:486) ~[jmix-core-1.0.1.jar:na]
	at io.jmix.securitydata.user.AbstractDatabaseUserRepository.loadUserByUsername(AbstractDatabaseUserRepository.java:187) ~[jmix-security-data-1.0.1.jar:na]
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:93) ~[spring-security-core-5.5.1.jar:5.5.1]
	... 100 common frames omitted
```

**Comment by reznikova21** [comment]
Jmix version: 1.0.999-SNAPSHOT - verified
