### ISSUE TITLE
Generated ID is null in io.jmix.reports.entity.BandDefinition-null

### ISSUE THREAD

**Issue by NikitaShchienko** [Haulmont/jmix-reports#23]
The floating issue is caused by multiple changes and saving the report on the report editor screen.

Stack trace:
```
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:157) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431) [vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396) [vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260) [vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82) [vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578) [vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) [vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) [javax.servlet-api-4.0.1.jar:4.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.1.jar:5.3.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.1.jar:5.3.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.4.1.jar:5.4.1]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.3.1.jar:5.3.1]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.3.1.jar:5.3.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.1.jar:5.3.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.1.jar:5.3.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.1.jar:5.3.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.1.jar:5.3.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.1.jar:5.3.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.1.jar:5.3.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_241]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_241]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        ... 83 common frames omitted
Caused by: java.lang.IllegalStateException: Generated ID is null in io.jmix.reports.entity.BandDefinition-null [new]
        at io.jmix.core.EntityEntry.getGeneratedId(EntityEntry.java:41) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.core.entity.BaseEntityEntry.hashCode(BaseEntityEntry.java:60) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.core.impl.EntityInternals.hashCode(EntityInternals.java:76) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.reports.entity.BandDefinition.hashCode(BandDefinition.java) ~[jmix-reports-0.3.0-SNAPSHOT.jar:na]
        at java.util.HashMap.hash(HashMap.java:339) ~[na:1.8.0_241]
        at java.util.HashMap.put(HashMap.java:612) ~[na:1.8.0_241]
        at java.util.HashSet.readObject(HashSet.java:342) ~[na:1.8.0_241]
        at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_241]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2232) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2123) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2341) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2265) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2123) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2341) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2265) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2123) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[na:1.8.0_241]
        at java.util.ArrayList.readObject(ArrayList.java:797) ~[na:1.8.0_241]
        at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_241]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2232) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2123) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464) ~[na:1.8.0_241]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[na:1.8.0_241]
        at io.jmix.core.impl.StandardSerialization.deserialize(StandardSerialization.java:74) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.core.impl.StandardSerialization.deserialize(StandardSerialization.java:96) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.model.impl.DataContextImpl.isolate(DataContextImpl.java:689) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.model.impl.DataContextImpl.commitToDataManager(DataContextImpl.java:664) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.model.impl.DataContextImpl.performCommit(DataContextImpl.java:656) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.model.impl.DataContextImpl.commit(DataContextImpl.java:617) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.screen.StandardEditor.lambda$commitChanges$4(StandardEditor.java:364) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.screen.StandardEditor.commitChanges(StandardEditor.java:379) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.screen.StandardEditor.commit(StandardEditor.java:498) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
        at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
        ... 87 common frames omitted

```

**Comment by NikitaShchienko** [comment]
Fixed to Haulmont/jmix-ui#243
