### ISSUE TITLE
Cannot get unfetched attribute [code] from detached object io.jmix.reports.entity.ReportGroup after report creating

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-reports#230]
**Environment:**
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.1.4-213
IntelliJ version: IntelliJ IDEA 2021.3.2 RC (Ultimate Edition)

**TC:**
1. Create a new project -> Add the reports add-on
2. Run the app -> Login as admin 
3. Reports -> Create a new report with any type for User entity using the wizard 
4. Do not choose manually report group in the final screen -> Save

**AR:**
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/3af4a657-bd33-4ecc-b724-4207c4585f07) 
```
Caused by: java.lang.IllegalStateException: Cannot get unfetched attribute [code] from detached object io.jmix.reports.entity.ReportGroup-4e083530-0b9c-11e1-9b41-6bdaa41bff94 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100) ~[org.eclipse.persistence.core-2.7.9-6-jmix.jar:na]
	at io.jmix.eclipselink.impl.JmixEntityFetchGroup.onUnfetchedAttribute(JmixEntityFetchGroup.java:67) ~[jmix-eclipselink-1.2.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3027) ~[org.eclipse.persistence.jpa-2.7.9-6-jmix.jar:na]
	at io.jmix.reports.entity.ReportGroup._persistence_checkFetched(ReportGroup.java) ~[jmix-reports-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.reports.entity.ReportGroup._persistence_get_code(ReportGroup.java) ~[jmix-reports-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.reports.entity.ReportGroup.getCode(ReportGroup.java:167) ~[jmix-reports-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:85) ~[jmix-core-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.core.entity.BaseEntityEntry.setAttributeValue(BaseEntityEntry.java:101) ~[jmix-core-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.core.entity.EntityValues.setValue(EntityValues.java:89) ~[jmix-core-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.DataContextImpl.setPropertyValue(DataContextImpl.java:342) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.DataContextImpl.setPropertyValue(DataContextImpl.java:336) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.DataContextImpl.mergeState(DataContextImpl.java:282) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.DataContextImpl.internalMerge(DataContextImpl.java:236) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.DataContextImpl.mergeState(DataContextImpl.java:312) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.DataContextImpl.internalMerge(DataContextImpl.java:225) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:157) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:166) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.builder.EditorBuilderProcessor.merge(EditorBuilderProcessor.java:199) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.builder.EditorBuilderProcessor.lambda$buildEditor$0(EditorBuilderProcessor.java:104) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.Screen.close(Screen.java:330) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.StandardEditor.lambda$closeWithCommit$11(StandardEditor.java:617) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.util.SuccessOperationResult.compose(SuccessOperationResult.java:35) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:617) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:570) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null

	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
Caused by: java.lang.IllegalStateException: Cannot get unfetched attribute [code] from detached object io.jmix.reports.entity.ReportGroup-4e083530-0b9c-11e1-9b41-6bdaa41bff94 [detached].

	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	... 87 common frames omitted
```

**Notes:**
if a report group was chosen manually, error is not displayed

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2.0-SNAPSHOT - veryfied
