### ISSUE TITLE
java.lang.IllegalStateException: Current item is null exception when closing the report editor

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-reports#29]
1. Open the report editor
1. Immediately click the **OK** button

Exception:
```
java.lang.IllegalStateException: Current item is null
	at io.jmix.ui.model.impl.InstanceContainerImpl.getItem(InstanceContainerImpl.java:74)
	at io.jmix.reportsui.screen.definition.edit.crosstab.CrossTabTableDecorator.isVerticalOrHorizontalCrossField(CrossTabTableDecorator.java:81)
	at io.jmix.reportsui.screen.definition.edit.crosstab.CrossTabTableDecorator.lambda$decorate$0(CrossTabTableDecorator.java:72)
	at io.jmix.ui.component.impl.AbstractTable$1.generateCell(AbstractTable.java:2612)
	at com.vaadin.v7.ui.Table.parseItemIdToCells(Table.java:2349)
	at com.vaadin.v7.ui.Table.getVisibleCellsNoCache(Table.java:2219)
	at com.vaadin.v7.ui.Table.refreshRenderedCells(Table.java:1762)
	at com.vaadin.v7.ui.Table.refreshRowCache(Table.java:2670)
	at io.jmix.ui.widget.JmixTable.refreshRowCache(JmixTable.java:1097)
	at com.vaadin.v7.ui.Table.containerItemSetChange(Table.java:4572)
	at io.jmix.ui.component.table.TableDataContainer.fireItemSetChanged(TableDataContainer.java:168)
	at io.jmix.ui.component.table.TableDataContainer.datasourceItemSetChanged(TableDataContainer.java:282)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.component.data.table.ContainerTableItems.containerCollectionChanged(ContainerTableItems.java:74)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.model.impl.CollectionContainerImpl.fireCollectionChanged(CollectionContainerImpl.java:241)
	at io.jmix.ui.model.impl.CollectionContainerImpl.setItems(CollectionContainerImpl.java:106)
	at io.jmix.ui.model.impl.CollectionPropertyContainerImpl.setDisconnectedItems(CollectionPropertyContainerImpl.java:58)
	at io.jmix.ui.model.DataComponents.lambda$createCollectionContainer$3(DataComponents.java:159)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.model.impl.InstanceContainerImpl.itemPropertyChanged(InstanceContainerImpl.java:182)
	at io.jmix.ui.model.impl.CollectionContainerImpl.itemPropertyChanged(CollectionContainerImpl.java:231)
	at io.jmix.core.entity.BaseEntityEntry.firePropertyChanged(BaseEntityEntry.java:187)
	at io.jmix.core.impl.EntityInternals.fireListeners(EntityInternals.java:84)
	at io.jmix.reports.entity.BandDefinition.setDataSets(BandDefinition.java:103)
	at io.jmix.core.metamodel.model.utils.MethodsCache$SettersHolder.accept(MethodsCache.java:188)
	at io.jmix.core.entity.BaseEntityEntry.setAttributeValue(BaseEntityEntry.java:93)
	at io.jmix.core.entity.EntityValues.setValue(EntityValues.java:83)
	at io.jmix.ui.model.impl.DataContextImpl.setPropertyValue(DataContextImpl.java:342)
	at io.jmix.ui.model.impl.DataContextImpl.setPropertyValue(DataContextImpl.java:336)
	at io.jmix.ui.model.impl.DataContextImpl.mergeList(DataContextImpl.java:400)
	at io.jmix.ui.model.impl.DataContextImpl.mergeState(DataContextImpl.java:304)
	at io.jmix.ui.model.impl.DataContextImpl.internalMerge(DataContextImpl.java:233)
	at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:177)
	at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:188)
	at io.jmix.ui.model.impl.DataContextImpl.mergeCommitted(DataContextImpl.java:771)
	at io.jmix.ui.model.impl.DataContextImpl.commit(DataContextImpl.java:647)
	at io.jmix.ui.screen.StandardEditor.lambda$commitChanges$8(StandardEditor.java:400)
	at io.jmix.ui.screen.StandardEditor.commitChanges(StandardEditor.java:415)
	at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:573)
	at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:530)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by m-orlova** [comment]
This exception is thrown also in the following case:

1. Create a report with default  template [Template.docx](https://github.com/Haulmont/jmix-reports/files/5980686/Template.docx)
2. Add new band with name ="Band" and add groovy dataset to the new band. Dataset has the following script:
 `return [['image': 'https://upload.wikimedia.org/wikipedia/ru/7/77/Pikachu.png']]`

![image](https://user-images.githubusercontent.com/71265042/107935781-44cf9180-6f9b-11eb-8c15-f1652566d73e.png)
3. Save the report
4. Reopen Report Browser, select created report and click on the "Edit" button
5. Select "Parameters and Formats" tab
6. Create a value format with "Name" = Band.image and "Format string"=${image:WxH}
7. Click "Ok" to save a value format

**Comment by KartonDCP** [comment]
I did same for this issue and comment later and didn't get any errors
