### ISSUE TITLE
java.lang.IllegalStateException: Datasource doesn't contain items exception when opening the report that has been just modified

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-reports#30]
1. Open the existing report editor
2. Do some modification, e.g.modify the script in Groovy dataset
3. Close the editor with the OK button
4. Try to open the editor for the same report again

AR: Exception:

```
java.lang.IllegalStateException: Datasource doesn't contain items
	at io.jmix.ui.component.impl.TreeImpl.setSelected(TreeImpl.java:1140)
	at io.jmix.ui.component.impl.TreeImpl.setSelected(TreeImpl.java:1128)
	at io.jmix.reportsui.screen.report.edit.ReportEditor.onBeforeShow(ReportEditor.java:171)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124)
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:58)
	at io.jmix.ui.sys.ScreensImpl.fireScreenBeforeShowEvent(ScreensImpl.java:1341)
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:353)
	at io.jmix.ui.screen.Screen.show(Screen.java:306)
	at io.jmix.ui.action.list.EditAction.execute(EditAction.java:366)
	at io.jmix.ui.action.list.EditAction.actionPerform(EditAction.java:313)
	at io.jmix.ui.component.impl.AbstractTable.handleClickAction(AbstractTable.java:1381)
	at io.jmix.ui.component.impl.AbstractTable.lambda$initComponent$db766529$1(AbstractTable.java:1119)
	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.v7.ui.Table.handleClickEvent(Table.java:3142)
	at com.vaadin.v7.ui.Table.changeVariables(Table.java:2934)
	at io.jmix.ui.widget.JmixTable.changeVariables(JmixTable.java:357)
	at io.jmix.ui.widget.JmixGroupTable.changeVariables(JmixGroupTable.java:297)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:611)
```

**Comment by NikitaShchienko** [comment]
Fixed in #25 

Band setting moved to `onAfterShow()`
