### ISSUE TITLE
NPE when trying to save changes to RegionEditor screen

### ISSUE THREAD

**Issue by NikitaShchienko** [Haulmont/jmix-reports#85]
**Test case:**
1. Create new report
2. Add a report parameter with the List of entities type, say orders
3. Create a new band and a dataset with the List of entities dataset type
4. Select the orders parameter in the List of entities parameter name lookup
5. Click the Select entity attribute button
6. Select attribute
7. Click the Save

**AR**: NullPointerException

```
java.lang.NullPointerException
	at io.jmix.reports.entity.wizard.ReportRegion.getNameForBand(ReportRegion.java:125)
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:74)
	at io.jmix.core.entity.EntityValues.getValue(EntityValues.java:94)
	at io.jmix.ui.model.impl.DataContextImpl.mergeState(DataContextImpl.java:276)
	at io.jmix.ui.model.impl.DataContextImpl.internalMerge(DataContextImpl.java:235)
	at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:179)
	at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:190)
	at io.jmix.ui.model.impl.DataContextImpl.mergeCommitted(DataContextImpl.java:773)
	at io.jmix.ui.model.impl.DataContextImpl.commit(DataContextImpl.java:649)
	at io.jmix.ui.screen.StandardEditor.lambda$commitChanges$9(StandardEditor.java:400)
	at io.jmix.ui.screen.StandardEditor$BeforeCommitChangesEvent.resume(StandardEditor.java:784)
	at io.jmix.reportsui.screen.report.wizard.region.RegionEditor.onBeforeCommit(RegionEditor.java:271)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124)
	at io.jmix.ui.screen.StandardEditor.commitChanges(StandardEditor.java:418)
	at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:589)
	at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:543)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
```

**Screenshot:**

![image](https://user-images.githubusercontent.com/47520144/113359028-f5c99a00-9357-11eb-9231-212c8a891849.png)

**Comment by gorbunkov** [comment]
@m-orlova This issue seems to be fixed. Check it please and close.

**Comment by m-orlova** [comment]
Can't reproduce
